import Head from "next/head";

type Restraunt = {
  name: string;
  address: string;
  rating: string;
}

export default function Home() {

  const restraunts: Restraunt[] = [
    {
      name: "McDonalds",
      address: "123 Fake Street",
      rating: "5 stars"
    },
    {
      name: "Burger King",
      address: "123 Fake Street",
      rating: "5 stars"
    },
    {
      name: "Wendys",
      address: "123 Fake Street",
      rating: "5 stars"
    }
  ]

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-6 p-8 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <section className="m-2 text-center text-white col-span-5">
          Map
        </section>
        <section className="flex flex-col space-y-2 ">
          {restraunts.map((restraunt, idx) => (
            <RestrauntCard key={idx} {...restraunt} />
          ))}

        </section>
      </main>
    </>
  );
}

const RestrauntCard: React.FC<{name: string, address: string, rating: string }> = ({name, address, rating}) => {
  return (
    <div className="transition-colors bg-gradient-to-tr  from-slate-200 via-slate-200/80 to-slate-200/60 p-4 rounded-xl hover:bg-slate-600">
      <div>{name}</div>
      <div>{address}</div>
      <div>{rating}</div>
    </div>
  )
}